### ISSUE TITLE
 In ownCloud v10.0.8 ，don't have  AfterLogic WebMail Settings 

### ISSUE THREAD

**Issue by arsenalpoll** [afterlogic/owncloud-connector#1]
AfterLogic WebMail is not configured properly yet. The administrator must configure AfterLogic WebMail first.

**Comment by afterlogic-support** [comment]
Are you able to use the WebMail installation directly? Thing is, the connector doesn't install webmail application, it's supposed to be there already. Once you have WebMail installed and configured, you can proceed with configuring the integration.
https://afterlogic.com/docs/webmail-lite-8/configuring-webmail/integration-with-owncloud
