### ISSUE TITLE
Afterlogic doesnt open

### ISSUE THREAD

**Issue by Puffel938** [afterlogic/owncloud-connector#2]
After configuration of afterlogic, the homescreen appears again when clicking on Mail.
![Unbenannt](https://user-images.githubusercontent.com/57215261/67934248-cd1ffc80-fbc7-11e9-8c7f-bb63db30dd34.PNG)

**Comment by afterlogic-support** [comment]
- Did you specify email and password in your owncloud account settings?
- Does Webmail open if you enter its direct URL?

**Comment by Puffel938** [comment]
The email settings are set.
But where can i configure the email-server?
Whats the direct url? I've installed it from the market.

**Comment by afterlogic-support** [comment]
Not sure what you're asking. This application is just a connector, it's required that you install WebMail Lite or Pro separately.

**Comment by Puffel938** [comment]
Ok. Thank you. Got it working.
I thougt the App in the market is a full client
