### ISSUE TITLE
Is it possible to use SSO

### ISSUE THREAD

**Issue by RaZer0r** [afterlogic/owncloud-connector#3]
Hi,

My current setup uses IMAP to logon at my owncloud instance.
With rainloop it is possible to use the same credentials and SSO into the webmail environment.

Can this also be done with the afterlogic webmail?

**Comment by afterlogic-support** [comment]
With WebMail connector for ownCloud installed, user gets settings for email/password in their ownCloud dashboard. With those settings filled, they will be logged into their WebMail account, bypassing login screen of WebMail.
