### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by grulles** [afterlogic/owncloud-connector#4]
Hello, 
I had installed afterlogic app + owncloud connector. 
I can reach the afterlogic from owncloud but authentication is always failed. I can't also save my credential for afterlogic in owncloud Invalid argument(s). 
Owncloud used dovecot + mysql for authentication. 
Thank you for your help.

**Comment by afterlogic-support** [comment]
Hello,
From your message, it's not clear whether you have Afterlogic WebMail installed, and if yes, which one. Please provide information on:
* Afterlogic product name and version;
* Owncloud version;
* Afterlogic app for Owncloud version.

With regard to saving credentials, make sure path and url of webmail installation are specified correctly in the owncloud app settings.

**Comment by afterlogic-support** [comment]
For testing purposes, I've just deployed a blank test environment using Ubuntu 18.04.5. Installed WebMail Lite 8 [from APT repository](https://afterlogic.com/docs/webmail-lite-8/installation/installing-on-debian-ubuntu-linux), Apache PHP and MySQL installed as dependencies. 
Installed and configured ownCloud 10.5.0, Afterlogic app from ownCloud market, version 1.2.3.
Everything worked as expected, I've configured WebMail itself, then specified URL and path of WebMail installation in connector settings, and was able to log into WebMail just fine.

**Comment by grulles** [comment]
Hello,
See version used  ; 
ownCloud 10.5.0  
Afterlofic app for owncloud :  1.2.3
 Afterlogic WebMail Lite PHP 8.5.2-build-a3 

I can log to owncloud with my email and my password, but webmail didn't accept my credential. 

Afterlogic is deployed in /var/www/html/webmail so the path iis configured like this in owncloud.
The configuration of mail server in afterlogic is configured to user my postfix and dovecot server (same fqdn) .

Thank you for your help. 
Regards Damien

**Comment by afterlogic-support** [comment]
Can you please confirm whether you're able to log into webmail directly, without using ownCloud, and authentication issue arises only when attempting to log into email account from ownCloud? Thank you.

**Comment by grulles** [comment]
Hello,
I'm not able to connect into webmail direcltly too? And after 3 unsuccessfull connection I have to wait 30'

**Comment by afterlogic-support** [comment]
> I'm not able to connect into webmail direcltly too? 

Understood, the issue isn't related to ownCloud then, you need to make sure WebMail is [configured correctly](https://afterlogic.com/docs/webmail-lite-8/configuring-webmail). And if you're getting any errors, be sure to [check the logs](https://afterlogic.com/docs/webmail-lite-8/troubleshooting/debug-logging-as-main-troubleshooting-measure).

> And after 3 unsuccessfull connection I have to wait 30

This protective feature can be adjusted in `data/settings/modules/Core.config.json` file:

```json
    "LoginBlockAvailableTriesCount": [
        3,
        "int"
    ],
    "LoginBlockDurationMinutes": [
        30,
        "int"
    ]
```

so you can either increase the first value or decrease the 2nd one. **EnableFailedLoginBlock** setting isn't actually used, and this will be corrected in the next release.
